-- Systems
INSERT INTO systems (system_id, name, version, mechanic_type) VALUES
(1, 'Dungeons & Dragons 5e', '5.0', 'D20'),
(2, 'Pathfinder 2e', '2.0', 'D20'),
(3, 'Call of Cthulhu', '7.0', 'Percentile'),
(4, 'Vampire: The Masquerade', '5.0', 'D10'),
(5, 'Cyberpunk Red', '1.0', 'D10'),
(6, 'Warhammer Fantasy Roleplay', '4.0', 'D100');

-- Attribute Definitions
INSERT INTO attribute_definitions (attr_def_id, system_id, name, abbreviation, data_type) VALUES
-- D&D 5e
(1, 1, 'Strength', 'STR', 'integer'),
(2, 1, 'Dexterity', 'DEX', 'integer'),
(3, 1, 'Constitution', 'CON', 'integer'),
(4, 1, 'Intelligence', 'INT', 'integer'),
(5, 1, 'Wisdom', 'WIS', 'integer'),
(6, 1, 'Charisma', 'CHA', 'integer'),
(7, 1, 'Hit Points', 'HP', 'integer'),
(8, 1, 'Armor Class', 'AC', 'integer'),
(9, 1, 'Level', 'LVL', 'integer'),
(10, 1, 'Challenge Rating', 'CR', 'integer'),
-- Pathfinder 2e
(11, 2, 'Strength', 'STR', 'integer'),
(12, 2, 'Dexterity', 'DEX', 'integer'),
(13, 2, 'Constitution', 'CON', 'integer'),
(14, 2, 'Intelligence', 'INT', 'integer'),
(15, 2, 'Wisdom', 'WIS', 'integer'),
(16, 2, 'Charisma', 'CHA', 'integer'),
(17, 2, 'Hit Points', 'HP', 'integer'),
(18, 2, 'Armor Class', 'AC', 'integer'),
(19, 2, 'Level', 'LVL', 'integer'),
(20, 2, 'Proficiency Bonus', 'PB', 'integer'),
-- Call of Cthulhu
(21, 3, 'Strength', 'STR', 'integer'),
(22, 3, 'Dexterity', 'DEX', 'integer'),
(23, 3, 'Constitution', 'CON', 'integer'),
(24, 3, 'Intelligence', 'INT', 'integer'),
(25, 3, 'Power', 'POW', 'integer'),
(26, 3, 'Charisma', 'CHA', 'integer'),
(27, 3, 'Sanity', 'SAN', 'integer'),
(28, 3, 'Hit Points', 'HP', 'integer'),
(29, 3, 'Magic Points', 'MP', 'integer'),
(30, 3, 'Luck', 'LCK', 'integer'),
-- Vampire: The Masquerade
(31, 4, 'Strength', 'STR', 'integer'),
(32, 4, 'Dexterity', 'DEX', 'integer'),
(33, 4, 'Stamina', 'STA', 'integer'),
(34, 4, 'Charisma', 'CHA', 'integer'),
(35, 4, 'Manipulation', 'MAN', 'integer'),
(36, 4, 'Composure', 'COM', 'integer'),
(37, 4, 'Intelligence', 'INT', 'integer'),
(38, 4, 'Wits', 'WITS', 'integer'),
(39, 4, 'Resolve', 'RES', 'integer'),
(40, 4, 'Humanity', 'HUM', 'integer'),
-- Cyberpunk Red
(41, 5, 'Intelligence', 'INT', 'integer'),
(42, 5, 'Reflex', 'REF', 'integer'),
(43, 5, 'Dexterity', 'DEX', 'integer'),
(44, 5, 'Technical Ability', 'TECH', 'integer'),
(45, 5, 'Cool', 'COOL', 'integer'),
(46, 5, 'Willpower', 'WILL', 'integer'),
(47, 5, 'Luck', 'LUCK', 'integer'),
(48, 5, 'Movement', 'MOVE', 'integer'),
(49, 5, 'Body', 'BODY', 'integer'),
(50, 5, 'Empathy', 'EMP', 'integer'),
-- Warhammer Fantasy
(51, 6, 'Weapon Skill', 'WS', 'integer'),
(52, 6, 'Ballistic Skill', 'BS', 'integer'),
(53, 6, 'Strength', 'S', 'integer'),
(54, 6, 'Toughness', 'T', 'integer'),
(55, 6, 'Initiative', 'I', 'integer'),
(56, 6, 'Agility', 'Ag', 'integer'),
(57, 6, 'Dexterity', 'Dex', 'integer'),
(58, 6, 'Intelligence', 'Int', 'integer'),
(59, 6, 'Willpower', 'WP', 'integer'),
(60, 6, 'Fellowship', 'Fel', 'integer');

-- Tags
INSERT INTO tags (tag_id, name) VALUES
(1, 'combat'),
(2, 'magic'),
(3, 'support'),
(4, 'damage'),
(5, 'healing'),
(6, 'utility'),
(7, 'social'),
(8, 'exploration'),
(9, 'supernatural'),
(10, 'technical'),
(11, 'cyberware'),
(12, 'firearms'),
(13, 'melee'),
(14, 'ranged'),
(15, 'armor'),
(16, 'weapon'),
(17, 'spell'),
(18, 'feat'),
(19, 'creature'),
(20, 'character'),
(21, 'npc'),
(22, 'pc'),
(23, 'legendary'),
(24, 'unique'),
(25, 'common'),
(26, 'rare'),
(27, 'epic'),
(28, 'level-1'),
(29, 'level-5'),
(30, 'level-10'),
(31, 'fire'),
(32, 'cold'),
(33, 'lightning'),
(34, 'acid'),
(35, 'poison'),
(36, 'psychic'),
(37, 'necromancy'),
(38, 'illusion'),
(39, 'enchantment'),
(40, 'evocation'),
(41, 'divination'),
(42, 'transmutation'),
(43, 'conjuration'),
(44, 'abjuration'),
(45, 'vampire'),
(46, 'zombie'),
(47, 'undead'),
(48, 'beast'),
(49, 'humanoid'),
(50, 'construct'),
(51, 'dragon'),
(52, 'elemental'),
(53, 'celestial'),
(54, 'fiend'),
(55, 'fey'),
(56, 'investigation'),
(57, 'stealth'),
(58, 'persuasion'),
(59, 'lore'),
(60, 'ritual');