-- Generated by import_bestiary.py
-- Source: bestiary-xphb.json
--
-- Use: sqlite3 Assets/5e_data.sqlite < Assets/import_bestiary.sql

PRAGMA foreign_keys = ON;
BEGIN TRANSACTION;

INSERT OR IGNORE INTO entities (id, name, entity_type, size, alignment, armor_class, armor_desc, hit_points_max, hit_points_current, hit_dice_max, hit_dice_current, hit_dice_type, speed_walk, speed_fly, speed_swim, speed_climb, speed_burrow, darkvision, blindsight, tremorsense, truesight, passive_perception_override, languages, notes)
  VALUES ('mon-31', 'Aberrant Spirit (Beholderkin)', 'creature', 'Medium', 'Neutral', 10, '11 + the spell''s level', 40, 40, 1, 1, 'd8', 30, 30, 0, 0, 0, 60, 0, 0, 0, 10, 'Deep Speech, understands the languages you know', 'Summoned by: Summon Aberration|XPHB; Spell level: 4; Source: XPHB; PB: equals your Proficiency Bonus');
INSERT OR IGNORE INTO entity_stats (entity_id, strength, dexterity, constitution, intelligence, wisdom, charisma)
  VALUES ('mon-31', 16, 10, 15, 16, 10, 6);
INSERT OR IGNORE INTO creature_profiles (entity_id, challenge_rating, xp_value, creature_type, creature_subtype, is_legendary, legendary_resistances_max, legendary_resistances_current)
  VALUES ('mon-31', 0.0, 0, 'Aberration', NULL, 0, 0, 0);
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-31', id FROM action_library WHERE name = 'Multiattack';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-31', id FROM action_library WHERE name = 'Eye Ray';
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-31', 'Psychic', 'immunity');

INSERT OR IGNORE INTO entities (id, name, entity_type, size, alignment, armor_class, armor_desc, hit_points_max, hit_points_current, hit_dice_max, hit_dice_current, hit_dice_type, speed_walk, speed_fly, speed_swim, speed_climb, speed_burrow, darkvision, blindsight, tremorsense, truesight, passive_perception_override, languages, notes)
  VALUES ('mon-32', 'Aberrant Spirit (Slaad)', 'creature', 'Medium', 'Neutral', 10, '11 + the spell''s level', 40, 40, 1, 1, 'd8', 30, 0, 0, 0, 0, 60, 0, 0, 0, 10, 'Deep Speech, understands the languages you know', 'Summoned by: Summon Aberration|XPHB; Spell level: 4; Source: XPHB; PB: equals your Proficiency Bonus');
INSERT OR IGNORE INTO entity_stats (entity_id, strength, dexterity, constitution, intelligence, wisdom, charisma)
  VALUES ('mon-32', 16, 10, 15, 16, 10, 6);
INSERT OR IGNORE INTO creature_profiles (entity_id, challenge_rating, xp_value, creature_type, creature_subtype, is_legendary, legendary_resistances_max, legendary_resistances_current)
  VALUES ('mon-32', 0.0, 0, 'Aberration', NULL, 0, 0, 0);
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-32', id FROM action_library WHERE name = 'Multiattack';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-32', id FROM action_library WHERE name = 'Claw';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-32', id FROM action_library WHERE name = 'Eye Ray';
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-32', 'Psychic', 'immunity');

INSERT OR IGNORE INTO entities (id, name, entity_type, size, alignment, armor_class, armor_desc, hit_points_max, hit_points_current, hit_dice_max, hit_dice_current, hit_dice_type, speed_walk, speed_fly, speed_swim, speed_climb, speed_burrow, darkvision, blindsight, tremorsense, truesight, passive_perception_override, languages, notes)
  VALUES ('mon-33', 'Aberrant Spirit (Star Spawn)', 'creature', 'Medium', 'Neutral', 10, '11 + the spell''s level', 40, 40, 1, 1, 'd8', 30, 0, 0, 0, 0, 60, 0, 0, 0, 10, 'Deep Speech, understands the languages you know', 'Summoned by: Summon Aberration|XPHB; Spell level: 4; Source: XPHB; PB: equals your Proficiency Bonus');
INSERT OR IGNORE INTO entity_stats (entity_id, strength, dexterity, constitution, intelligence, wisdom, charisma)
  VALUES ('mon-33', 16, 10, 15, 16, 10, 6);
INSERT OR IGNORE INTO creature_profiles (entity_id, challenge_rating, xp_value, creature_type, creature_subtype, is_legendary, legendary_resistances_max, legendary_resistances_current)
  VALUES ('mon-33', 0.0, 0, 'Aberration', NULL, 0, 0, 0);
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-33', id FROM action_library WHERE name = 'Multiattack';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-33', id FROM action_library WHERE name = 'Claw';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-33', id FROM action_library WHERE name = 'Eye Ray';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-33', id FROM action_library WHERE name = 'Psychic Slam';
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-33', 'Psychic', 'immunity');

INSERT OR IGNORE INTO entities (id, name, entity_type, size, alignment, armor_class, armor_desc, hit_points_max, hit_points_current, hit_dice_max, hit_dice_current, hit_dice_type, speed_walk, speed_fly, speed_swim, speed_climb, speed_burrow, darkvision, blindsight, tremorsense, truesight, passive_perception_override, languages, notes)
  VALUES ('mon-34', 'Animated Object (Medium or Smaller)', 'creature', 'Tiny', 'Unaligned', 15, NULL, 10, 10, 1, 1, 'd8', 30, 0, 0, 0, 0, 0, 30, 0, 0, 6, 'understands the languages you know', 'Summoned by: Animate Objects|XPHB; Spell level: 5; Source: XPHB; PB: equals your Proficiency Bonus');
INSERT OR IGNORE INTO entity_stats (entity_id, strength, dexterity, constitution, intelligence, wisdom, charisma)
  VALUES ('mon-34', 16, 10, 10, 3, 3, 1);
INSERT OR IGNORE INTO creature_profiles (entity_id, challenge_rating, xp_value, creature_type, creature_subtype, is_legendary, legendary_resistances_max, legendary_resistances_current)
  VALUES ('mon-34', 0.0, 0, 'Construct', NULL, 0, 0, 0);
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-34', id FROM action_library WHERE name = 'Slam';

INSERT OR IGNORE INTO entities (id, name, entity_type, size, alignment, armor_class, armor_desc, hit_points_max, hit_points_current, hit_dice_max, hit_dice_current, hit_dice_type, speed_walk, speed_fly, speed_swim, speed_climb, speed_burrow, darkvision, blindsight, tremorsense, truesight, passive_perception_override, languages, notes)
  VALUES ('mon-35', 'Beast of the Land', 'creature', 'Medium', 'Neutral', 10, '13 plus your Wisdom modifier', 5, 5, 1, 1, 'd8', 40, 0, 0, 40, 0, 60, 0, 0, 0, 12, 'understands the languages you know', 'Source: XPHB; PB: equals your Proficiency Bonus');
INSERT OR IGNORE INTO entity_stats (entity_id, strength, dexterity, constitution, intelligence, wisdom, charisma)
  VALUES ('mon-35', 14, 14, 15, 8, 14, 11);
INSERT OR IGNORE INTO creature_profiles (entity_id, challenge_rating, xp_value, creature_type, creature_subtype, is_legendary, legendary_resistances_max, legendary_resistances_current)
  VALUES ('mon-35', 0.0, 0, 'Beast', NULL, 0, 0, 0);
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-35', id FROM action_library WHERE name = 'Beast''s Strike';

INSERT OR IGNORE INTO entities (id, name, entity_type, size, alignment, armor_class, armor_desc, hit_points_max, hit_points_current, hit_dice_max, hit_dice_current, hit_dice_type, speed_walk, speed_fly, speed_swim, speed_climb, speed_burrow, darkvision, blindsight, tremorsense, truesight, passive_perception_override, languages, notes)
  VALUES ('mon-36', 'Beast of the Sea', 'creature', 'Medium', 'Neutral', 10, '13 plus your Wisdom modifier', 5, 5, 1, 1, 'd8', 5, 0, 60, 0, 0, 90, 0, 0, 0, 12, 'understands the languages you know', 'Source: XPHB; PB: equals your Proficiency Bonus');
INSERT OR IGNORE INTO entity_stats (entity_id, strength, dexterity, constitution, intelligence, wisdom, charisma)
  VALUES ('mon-36', 14, 14, 15, 8, 14, 11);
INSERT OR IGNORE INTO creature_profiles (entity_id, challenge_rating, xp_value, creature_type, creature_subtype, is_legendary, legendary_resistances_max, legendary_resistances_current)
  VALUES ('mon-36', 0.0, 0, 'Beast', NULL, 0, 0, 0);
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-36', id FROM action_library WHERE name = 'Beast''s Strike';

INSERT OR IGNORE INTO entities (id, name, entity_type, size, alignment, armor_class, armor_desc, hit_points_max, hit_points_current, hit_dice_max, hit_dice_current, hit_dice_type, speed_walk, speed_fly, speed_swim, speed_climb, speed_burrow, darkvision, blindsight, tremorsense, truesight, passive_perception_override, languages, notes)
  VALUES ('mon-37', 'Beast of the Sky', 'creature', 'Small', 'Neutral', 10, '13 plus your Wisdom modifier', 4, 4, 1, 1, 'd8', 10, 60, 0, 0, 0, 60, 0, 0, 0, 12, 'understands the languages you know', 'Source: XPHB; PB: equals your Proficiency Bonus');
INSERT OR IGNORE INTO entity_stats (entity_id, strength, dexterity, constitution, intelligence, wisdom, charisma)
  VALUES ('mon-37', 6, 16, 13, 8, 14, 11);
INSERT OR IGNORE INTO creature_profiles (entity_id, challenge_rating, xp_value, creature_type, creature_subtype, is_legendary, legendary_resistances_max, legendary_resistances_current)
  VALUES ('mon-37', 0.0, 0, 'Beast', NULL, 0, 0, 0);
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-37', id FROM action_library WHERE name = 'Beast''s Strike';

INSERT OR IGNORE INTO entities (id, name, entity_type, size, alignment, armor_class, armor_desc, hit_points_max, hit_points_current, hit_dice_max, hit_dice_current, hit_dice_type, speed_walk, speed_fly, speed_swim, speed_climb, speed_burrow, darkvision, blindsight, tremorsense, truesight, passive_perception_override, languages, notes)
  VALUES ('mon-38', 'Bestial Spirit (Air)', 'creature', 'Small', 'Neutral', 10, '11 + the spell''s level', 20, 20, 1, 1, 'd8', 30, 60, 0, 0, 0, 60, 0, 0, 0, 12, 'understands the languages you know', 'Summoned by: Summon Beast|XPHB; Spell level: 2; Source: XPHB; PB: equals your Proficiency Bonus');
INSERT OR IGNORE INTO entity_stats (entity_id, strength, dexterity, constitution, intelligence, wisdom, charisma)
  VALUES ('mon-38', 18, 11, 16, 4, 14, 5);
INSERT OR IGNORE INTO creature_profiles (entity_id, challenge_rating, xp_value, creature_type, creature_subtype, is_legendary, legendary_resistances_max, legendary_resistances_current)
  VALUES ('mon-38', 0.0, 0, 'Beast', NULL, 0, 0, 0);
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-38', id FROM action_library WHERE name = 'Multiattack';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-38', id FROM action_library WHERE name = 'Rend';

INSERT OR IGNORE INTO entities (id, name, entity_type, size, alignment, armor_class, armor_desc, hit_points_max, hit_points_current, hit_dice_max, hit_dice_current, hit_dice_type, speed_walk, speed_fly, speed_swim, speed_climb, speed_burrow, darkvision, blindsight, tremorsense, truesight, passive_perception_override, languages, notes)
  VALUES ('mon-39', 'Bestial Spirit (Land)', 'creature', 'Small', 'Neutral', 10, '11 + the spell''s level', 30, 30, 1, 1, 'd8', 30, 0, 0, 30, 0, 60, 0, 0, 0, 12, 'understands the languages you know', 'Summoned by: Summon Beast|XPHB; Spell level: 2; Source: XPHB; PB: equals your Proficiency Bonus');
INSERT OR IGNORE INTO entity_stats (entity_id, strength, dexterity, constitution, intelligence, wisdom, charisma)
  VALUES ('mon-39', 18, 11, 16, 4, 14, 5);
INSERT OR IGNORE INTO creature_profiles (entity_id, challenge_rating, xp_value, creature_type, creature_subtype, is_legendary, legendary_resistances_max, legendary_resistances_current)
  VALUES ('mon-39', 0.0, 0, 'Beast', NULL, 0, 0, 0);
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-39', id FROM action_library WHERE name = 'Multiattack';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-39', id FROM action_library WHERE name = 'Rend';

INSERT OR IGNORE INTO entities (id, name, entity_type, size, alignment, armor_class, armor_desc, hit_points_max, hit_points_current, hit_dice_max, hit_dice_current, hit_dice_type, speed_walk, speed_fly, speed_swim, speed_climb, speed_burrow, darkvision, blindsight, tremorsense, truesight, passive_perception_override, languages, notes)
  VALUES ('mon-40', 'Bestial Spirit (Water)', 'creature', 'Small', 'Neutral', 10, '11 + the spell''s level', 30, 30, 1, 1, 'd8', 30, 0, 30, 0, 0, 60, 0, 0, 0, 12, 'understands the languages you know', 'Summoned by: Summon Beast|XPHB; Spell level: 2; Source: XPHB; PB: equals your Proficiency Bonus');
INSERT OR IGNORE INTO entity_stats (entity_id, strength, dexterity, constitution, intelligence, wisdom, charisma)
  VALUES ('mon-40', 18, 11, 16, 4, 14, 5);
INSERT OR IGNORE INTO creature_profiles (entity_id, challenge_rating, xp_value, creature_type, creature_subtype, is_legendary, legendary_resistances_max, legendary_resistances_current)
  VALUES ('mon-40', 0.0, 0, 'Beast', NULL, 0, 0, 0);
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-40', id FROM action_library WHERE name = 'Multiattack';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-40', id FROM action_library WHERE name = 'Rend';

INSERT OR IGNORE INTO entities (id, name, entity_type, size, alignment, armor_class, armor_desc, hit_points_max, hit_points_current, hit_dice_max, hit_dice_current, hit_dice_type, speed_walk, speed_fly, speed_swim, speed_climb, speed_burrow, darkvision, blindsight, tremorsense, truesight, passive_perception_override, languages, notes)
  VALUES ('mon-41', 'Celestial Spirit (Avenger)', 'creature', 'Large', 'Neutral', 10, '11 + the spell''s level', 40, 40, 1, 1, 'd8', 30, 40, 0, 0, 0, 60, 0, 0, 0, 12, 'Celestial, understands the languages you know', 'Summoned by: Summon Celestial|XPHB; Spell level: 5; Source: XPHB; PB: equals your Proficiency Bonus');
INSERT OR IGNORE INTO entity_stats (entity_id, strength, dexterity, constitution, intelligence, wisdom, charisma)
  VALUES ('mon-41', 16, 14, 16, 10, 14, 16);
INSERT OR IGNORE INTO creature_profiles (entity_id, challenge_rating, xp_value, creature_type, creature_subtype, is_legendary, legendary_resistances_max, legendary_resistances_current)
  VALUES ('mon-41', 0.0, 0, 'Celestial', NULL, 0, 0, 0);
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-41', id FROM action_library WHERE name = 'Multiattack';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-41', id FROM action_library WHERE name = 'Radiant Bow';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-41', id FROM action_library WHERE name = 'Healing Touch (1/Day)';
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-41', 'Radiant', 'resistance');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-41', 'Charmed');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-41', 'Frightened');

INSERT OR IGNORE INTO entities (id, name, entity_type, size, alignment, armor_class, armor_desc, hit_points_max, hit_points_current, hit_dice_max, hit_dice_current, hit_dice_type, speed_walk, speed_fly, speed_swim, speed_climb, speed_burrow, darkvision, blindsight, tremorsense, truesight, passive_perception_override, languages, notes)
  VALUES ('mon-42', 'Celestial Spirit (Defender)', 'creature', 'Large', 'Neutral', 10, '13 + the spell''s level', 40, 40, 1, 1, 'd8', 30, 40, 0, 0, 0, 60, 0, 0, 0, 12, 'Celestial, understands the languages you know', 'Summoned by: Summon Celestial|XPHB; Spell level: 5; Source: XPHB; PB: equals your Proficiency Bonus');
INSERT OR IGNORE INTO entity_stats (entity_id, strength, dexterity, constitution, intelligence, wisdom, charisma)
  VALUES ('mon-42', 16, 14, 16, 10, 14, 16);
INSERT OR IGNORE INTO creature_profiles (entity_id, challenge_rating, xp_value, creature_type, creature_subtype, is_legendary, legendary_resistances_max, legendary_resistances_current)
  VALUES ('mon-42', 0.0, 0, 'Celestial', NULL, 0, 0, 0);
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-42', id FROM action_library WHERE name = 'Multiattack';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-42', id FROM action_library WHERE name = 'Radiant Mace';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-42', id FROM action_library WHERE name = 'Healing Touch (1/Day)';
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-42', 'Radiant', 'resistance');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-42', 'Charmed');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-42', 'Frightened');

INSERT OR IGNORE INTO entities (id, name, entity_type, size, alignment, armor_class, armor_desc, hit_points_max, hit_points_current, hit_dice_max, hit_dice_current, hit_dice_type, speed_walk, speed_fly, speed_swim, speed_climb, speed_burrow, darkvision, blindsight, tremorsense, truesight, passive_perception_override, languages, notes)
  VALUES ('mon-43', 'Construct Spirit (Clay)', 'creature', 'Medium', 'Neutral', 10, '13 + the spell''s level', 40, 40, 1, 1, 'd8', 30, 0, 0, 0, 0, 60, 0, 0, 0, 10, 'Understands the languages you know', 'Summoned by: Summon Construct|XPHB; Spell level: 4; Source: XPHB; PB: equals your Proficiency Bonus');
INSERT OR IGNORE INTO entity_stats (entity_id, strength, dexterity, constitution, intelligence, wisdom, charisma)
  VALUES ('mon-43', 18, 10, 18, 14, 11, 5);
INSERT OR IGNORE INTO creature_profiles (entity_id, challenge_rating, xp_value, creature_type, creature_subtype, is_legendary, legendary_resistances_max, legendary_resistances_current)
  VALUES ('mon-43', 0.0, 0, 'Construct', NULL, 0, 0, 0);
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-43', id FROM action_library WHERE name = 'Multiattack';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-43', id FROM action_library WHERE name = 'Slam';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-43', id FROM action_library WHERE name = 'Berserk Lashing';
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-43', 'Poison', 'resistance');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-43', 'Charmed');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-43', 'Exhaustion');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-43', 'Frightened');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-43', 'Paralyzed');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-43', 'Poisoned');

INSERT OR IGNORE INTO entities (id, name, entity_type, size, alignment, armor_class, armor_desc, hit_points_max, hit_points_current, hit_dice_max, hit_dice_current, hit_dice_type, speed_walk, speed_fly, speed_swim, speed_climb, speed_burrow, darkvision, blindsight, tremorsense, truesight, passive_perception_override, languages, notes)
  VALUES ('mon-44', 'Construct Spirit (Metal)', 'creature', 'Medium', 'Neutral', 10, '13 + the spell''s level', 40, 40, 1, 1, 'd8', 30, 0, 0, 0, 0, 60, 0, 0, 0, 10, 'Understands the languages you know', 'Summoned by: Summon Construct|XPHB; Spell level: 4; Source: XPHB; PB: equals your Proficiency Bonus');
INSERT OR IGNORE INTO entity_stats (entity_id, strength, dexterity, constitution, intelligence, wisdom, charisma)
  VALUES ('mon-44', 18, 10, 18, 14, 11, 5);
INSERT OR IGNORE INTO creature_profiles (entity_id, challenge_rating, xp_value, creature_type, creature_subtype, is_legendary, legendary_resistances_max, legendary_resistances_current)
  VALUES ('mon-44', 0.0, 0, 'Construct', NULL, 0, 0, 0);
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-44', id FROM action_library WHERE name = 'Multiattack';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-44', id FROM action_library WHERE name = 'Slam';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-44', id FROM action_library WHERE name = 'Berserk Lashing';
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-44', 'Poison', 'resistance');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-44', 'Charmed');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-44', 'Exhaustion');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-44', 'Frightened');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-44', 'Paralyzed');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-44', 'Poisoned');

INSERT OR IGNORE INTO entities (id, name, entity_type, size, alignment, armor_class, armor_desc, hit_points_max, hit_points_current, hit_dice_max, hit_dice_current, hit_dice_type, speed_walk, speed_fly, speed_swim, speed_climb, speed_burrow, darkvision, blindsight, tremorsense, truesight, passive_perception_override, languages, notes)
  VALUES ('mon-45', 'Construct Spirit (Stone)', 'creature', 'Medium', 'Neutral', 10, '13 + the spell''s level', 40, 40, 1, 1, 'd8', 30, 0, 0, 0, 0, 60, 0, 0, 0, 10, 'Understands the languages you know', 'Summoned by: Summon Construct|XPHB; Spell level: 4; Source: XPHB; PB: equals your Proficiency Bonus');
INSERT OR IGNORE INTO entity_stats (entity_id, strength, dexterity, constitution, intelligence, wisdom, charisma)
  VALUES ('mon-45', 18, 10, 18, 14, 11, 5);
INSERT OR IGNORE INTO creature_profiles (entity_id, challenge_rating, xp_value, creature_type, creature_subtype, is_legendary, legendary_resistances_max, legendary_resistances_current)
  VALUES ('mon-45', 0.0, 0, 'Construct', NULL, 0, 0, 0);
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-45', id FROM action_library WHERE name = 'Multiattack';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-45', id FROM action_library WHERE name = 'Slam';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-45', id FROM action_library WHERE name = 'Berserk Lashing';
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-45', 'Poison', 'resistance');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-45', 'Charmed');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-45', 'Exhaustion');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-45', 'Frightened');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-45', 'Paralyzed');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-45', 'Poisoned');

INSERT OR IGNORE INTO entities (id, name, entity_type, size, alignment, armor_class, armor_desc, hit_points_max, hit_points_current, hit_dice_max, hit_dice_current, hit_dice_type, speed_walk, speed_fly, speed_swim, speed_climb, speed_burrow, darkvision, blindsight, tremorsense, truesight, passive_perception_override, languages, notes)
  VALUES ('mon-46', 'Draconic Spirit (Acid)', 'creature', 'Large', 'Neutral', 10, '14 + the spell''s level', 50, 50, 1, 1, 'd8', 30, 60, 30, 0, 0, 60, 30, 0, 0, 12, 'Draconic, understands the languages you know', 'Summoned by: Summon Dragon|XPHB; Spell level: 5; Source: XPHB; PB: equals your Proficiency Bonus');
INSERT OR IGNORE INTO entity_stats (entity_id, strength, dexterity, constitution, intelligence, wisdom, charisma)
  VALUES ('mon-46', 19, 14, 17, 10, 14, 14);
INSERT OR IGNORE INTO creature_profiles (entity_id, challenge_rating, xp_value, creature_type, creature_subtype, is_legendary, legendary_resistances_max, legendary_resistances_current)
  VALUES ('mon-46', 0.0, 0, 'Dragon', NULL, 0, 0, 0);
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-46', id FROM action_library WHERE name = 'Multiattack';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-46', id FROM action_library WHERE name = 'Rend';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-46', id FROM action_library WHERE name = 'Breath Weapon';
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-46', 'Acid', 'resistance');
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-46', 'Cold', 'resistance');
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-46', 'Fire', 'resistance');
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-46', 'Lightning', 'resistance');
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-46', 'Poison', 'resistance');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-46', 'Charmed');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-46', 'Frightened');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-46', 'Poisoned');

INSERT OR IGNORE INTO entities (id, name, entity_type, size, alignment, armor_class, armor_desc, hit_points_max, hit_points_current, hit_dice_max, hit_dice_current, hit_dice_type, speed_walk, speed_fly, speed_swim, speed_climb, speed_burrow, darkvision, blindsight, tremorsense, truesight, passive_perception_override, languages, notes)
  VALUES ('mon-47', 'Draconic Spirit (Cold)', 'creature', 'Large', 'Neutral', 10, '14 + the spell''s level', 50, 50, 1, 1, 'd8', 30, 60, 30, 0, 0, 60, 30, 0, 0, 12, 'Draconic, understands the languages you know', 'Summoned by: Summon Dragon|XPHB; Spell level: 5; Source: XPHB; PB: equals your Proficiency Bonus');
INSERT OR IGNORE INTO entity_stats (entity_id, strength, dexterity, constitution, intelligence, wisdom, charisma)
  VALUES ('mon-47', 19, 14, 17, 10, 14, 14);
INSERT OR IGNORE INTO creature_profiles (entity_id, challenge_rating, xp_value, creature_type, creature_subtype, is_legendary, legendary_resistances_max, legendary_resistances_current)
  VALUES ('mon-47', 0.0, 0, 'Dragon', NULL, 0, 0, 0);
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-47', id FROM action_library WHERE name = 'Multiattack';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-47', id FROM action_library WHERE name = 'Rend';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-47', id FROM action_library WHERE name = 'Breath Weapon';
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-47', 'Acid', 'resistance');
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-47', 'Cold', 'resistance');
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-47', 'Fire', 'resistance');
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-47', 'Lightning', 'resistance');
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-47', 'Poison', 'resistance');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-47', 'Charmed');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-47', 'Frightened');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-47', 'Poisoned');

INSERT OR IGNORE INTO entities (id, name, entity_type, size, alignment, armor_class, armor_desc, hit_points_max, hit_points_current, hit_dice_max, hit_dice_current, hit_dice_type, speed_walk, speed_fly, speed_swim, speed_climb, speed_burrow, darkvision, blindsight, tremorsense, truesight, passive_perception_override, languages, notes)
  VALUES ('mon-48', 'Draconic Spirit (Fire)', 'creature', 'Large', 'Neutral', 10, '14 + the spell''s level', 50, 50, 1, 1, 'd8', 30, 60, 30, 0, 0, 60, 30, 0, 0, 12, 'Draconic, understands the languages you know', 'Summoned by: Summon Dragon|XPHB; Spell level: 5; Source: XPHB; PB: equals your Proficiency Bonus');
INSERT OR IGNORE INTO entity_stats (entity_id, strength, dexterity, constitution, intelligence, wisdom, charisma)
  VALUES ('mon-48', 19, 14, 17, 10, 14, 14);
INSERT OR IGNORE INTO creature_profiles (entity_id, challenge_rating, xp_value, creature_type, creature_subtype, is_legendary, legendary_resistances_max, legendary_resistances_current)
  VALUES ('mon-48', 0.0, 0, 'Dragon', NULL, 0, 0, 0);
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-48', id FROM action_library WHERE name = 'Multiattack';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-48', id FROM action_library WHERE name = 'Rend';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-48', id FROM action_library WHERE name = 'Breath Weapon';
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-48', 'Acid', 'resistance');
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-48', 'Cold', 'resistance');
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-48', 'Fire', 'resistance');
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-48', 'Lightning', 'resistance');
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-48', 'Poison', 'resistance');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-48', 'Charmed');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-48', 'Frightened');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-48', 'Poisoned');

INSERT OR IGNORE INTO entities (id, name, entity_type, size, alignment, armor_class, armor_desc, hit_points_max, hit_points_current, hit_dice_max, hit_dice_current, hit_dice_type, speed_walk, speed_fly, speed_swim, speed_climb, speed_burrow, darkvision, blindsight, tremorsense, truesight, passive_perception_override, languages, notes)
  VALUES ('mon-49', 'Draconic Spirit (Lightning)', 'creature', 'Large', 'Neutral', 10, '14 + the spell''s level', 50, 50, 1, 1, 'd8', 30, 60, 30, 0, 0, 60, 30, 0, 0, 12, 'Draconic, understands the languages you know', 'Summoned by: Summon Dragon|XPHB; Spell level: 5; Source: XPHB; PB: equals your Proficiency Bonus');
INSERT OR IGNORE INTO entity_stats (entity_id, strength, dexterity, constitution, intelligence, wisdom, charisma)
  VALUES ('mon-49', 19, 14, 17, 10, 14, 14);
INSERT OR IGNORE INTO creature_profiles (entity_id, challenge_rating, xp_value, creature_type, creature_subtype, is_legendary, legendary_resistances_max, legendary_resistances_current)
  VALUES ('mon-49', 0.0, 0, 'Dragon', NULL, 0, 0, 0);
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-49', id FROM action_library WHERE name = 'Multiattack';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-49', id FROM action_library WHERE name = 'Rend';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-49', id FROM action_library WHERE name = 'Breath Weapon';
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-49', 'Acid', 'resistance');
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-49', 'Cold', 'resistance');
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-49', 'Fire', 'resistance');
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-49', 'Lightning', 'resistance');
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-49', 'Poison', 'resistance');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-49', 'Charmed');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-49', 'Frightened');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-49', 'Poisoned');

INSERT OR IGNORE INTO entities (id, name, entity_type, size, alignment, armor_class, armor_desc, hit_points_max, hit_points_current, hit_dice_max, hit_dice_current, hit_dice_type, speed_walk, speed_fly, speed_swim, speed_climb, speed_burrow, darkvision, blindsight, tremorsense, truesight, passive_perception_override, languages, notes)
  VALUES ('mon-50', 'Draconic Spirit (Poison)', 'creature', 'Large', 'Neutral', 10, '14 + the spell''s level', 50, 50, 1, 1, 'd8', 30, 60, 30, 0, 0, 60, 30, 0, 0, 12, 'Draconic, understands the languages you know', 'Summoned by: Summon Dragon|XPHB; Spell level: 5; Source: XPHB; PB: equals your Proficiency Bonus');
INSERT OR IGNORE INTO entity_stats (entity_id, strength, dexterity, constitution, intelligence, wisdom, charisma)
  VALUES ('mon-50', 19, 14, 17, 10, 14, 14);
INSERT OR IGNORE INTO creature_profiles (entity_id, challenge_rating, xp_value, creature_type, creature_subtype, is_legendary, legendary_resistances_max, legendary_resistances_current)
  VALUES ('mon-50', 0.0, 0, 'Dragon', NULL, 0, 0, 0);
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-50', id FROM action_library WHERE name = 'Multiattack';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-50', id FROM action_library WHERE name = 'Rend';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-50', id FROM action_library WHERE name = 'Breath Weapon';
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-50', 'Acid', 'resistance');
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-50', 'Cold', 'resistance');
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-50', 'Fire', 'resistance');
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-50', 'Lightning', 'resistance');
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-50', 'Poison', 'resistance');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-50', 'Charmed');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-50', 'Frightened');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-50', 'Poisoned');

INSERT OR IGNORE INTO entities (id, name, entity_type, size, alignment, armor_class, armor_desc, hit_points_max, hit_points_current, hit_dice_max, hit_dice_current, hit_dice_type, speed_walk, speed_fly, speed_swim, speed_climb, speed_burrow, darkvision, blindsight, tremorsense, truesight, passive_perception_override, languages, notes)
  VALUES ('mon-51', 'Elemental Spirit (Air)', 'creature', 'Medium', 'Neutral', 10, '11 + the spell''s level', 50, 50, 1, 1, 'd8', 40, 40, 0, 0, 0, 60, 0, 0, 0, 10, 'Primordial, understands the languages you know', 'Summoned by: Summon Elemental|XPHB; Spell level: 4; Source: XPHB; PB: equals your Proficiency Bonus');
INSERT OR IGNORE INTO entity_stats (entity_id, strength, dexterity, constitution, intelligence, wisdom, charisma)
  VALUES ('mon-51', 18, 15, 17, 4, 10, 16);
INSERT OR IGNORE INTO creature_profiles (entity_id, challenge_rating, xp_value, creature_type, creature_subtype, is_legendary, legendary_resistances_max, legendary_resistances_current)
  VALUES ('mon-51', 0.0, 0, 'Elemental', NULL, 0, 0, 0);
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-51', id FROM action_library WHERE name = 'Multiattack';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-51', id FROM action_library WHERE name = 'Slam';
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-51', 'Poison', 'immunity');
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-51', 'Lightning', 'resistance');
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-51', 'Thunder', 'resistance');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-51', 'Exhaustion');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-51', 'Paralyzed');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-51', 'Petrified');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-51', 'Poisoned');

INSERT OR IGNORE INTO entities (id, name, entity_type, size, alignment, armor_class, armor_desc, hit_points_max, hit_points_current, hit_dice_max, hit_dice_current, hit_dice_type, speed_walk, speed_fly, speed_swim, speed_climb, speed_burrow, darkvision, blindsight, tremorsense, truesight, passive_perception_override, languages, notes)
  VALUES ('mon-52', 'Elemental Spirit (Earth)', 'creature', 'Medium', 'Neutral', 10, '11 + the spell''s level', 50, 50, 1, 1, 'd8', 40, 0, 0, 0, 40, 60, 0, 0, 0, 10, 'Primordial, understands the languages you know', 'Summoned by: Summon Elemental|XPHB; Spell level: 4; Source: XPHB; PB: equals your Proficiency Bonus');
INSERT OR IGNORE INTO entity_stats (entity_id, strength, dexterity, constitution, intelligence, wisdom, charisma)
  VALUES ('mon-52', 18, 15, 17, 4, 10, 16);
INSERT OR IGNORE INTO creature_profiles (entity_id, challenge_rating, xp_value, creature_type, creature_subtype, is_legendary, legendary_resistances_max, legendary_resistances_current)
  VALUES ('mon-52', 0.0, 0, 'Elemental', NULL, 0, 0, 0);
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-52', id FROM action_library WHERE name = 'Multiattack';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-52', id FROM action_library WHERE name = 'Slam';
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-52', 'Poison', 'immunity');
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-52', 'Piercing', 'resistance');
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-52', 'Slashing', 'resistance');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-52', 'Exhaustion');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-52', 'Paralyzed');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-52', 'Petrified');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-52', 'Poisoned');

INSERT OR IGNORE INTO entities (id, name, entity_type, size, alignment, armor_class, armor_desc, hit_points_max, hit_points_current, hit_dice_max, hit_dice_current, hit_dice_type, speed_walk, speed_fly, speed_swim, speed_climb, speed_burrow, darkvision, blindsight, tremorsense, truesight, passive_perception_override, languages, notes)
  VALUES ('mon-53', 'Elemental Spirit (Fire)', 'creature', 'Medium', 'Neutral', 10, '11 + the spell''s level', 50, 50, 1, 1, 'd8', 40, 0, 0, 0, 0, 60, 0, 0, 0, 10, 'Primordial, understands the languages you know', 'Summoned by: Summon Elemental|XPHB; Spell level: 4; Source: XPHB; PB: equals your Proficiency Bonus');
INSERT OR IGNORE INTO entity_stats (entity_id, strength, dexterity, constitution, intelligence, wisdom, charisma)
  VALUES ('mon-53', 18, 15, 17, 4, 10, 16);
INSERT OR IGNORE INTO creature_profiles (entity_id, challenge_rating, xp_value, creature_type, creature_subtype, is_legendary, legendary_resistances_max, legendary_resistances_current)
  VALUES ('mon-53', 0.0, 0, 'Elemental', NULL, 0, 0, 0);
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-53', id FROM action_library WHERE name = 'Multiattack';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-53', id FROM action_library WHERE name = 'Slam';
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-53', 'Poison', 'immunity');
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-53', 'Fire', 'immunity');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-53', 'Exhaustion');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-53', 'Paralyzed');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-53', 'Petrified');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-53', 'Poisoned');

INSERT OR IGNORE INTO entities (id, name, entity_type, size, alignment, armor_class, armor_desc, hit_points_max, hit_points_current, hit_dice_max, hit_dice_current, hit_dice_type, speed_walk, speed_fly, speed_swim, speed_climb, speed_burrow, darkvision, blindsight, tremorsense, truesight, passive_perception_override, languages, notes)
  VALUES ('mon-54', 'Elemental Spirit (Water)', 'creature', 'Medium', 'Neutral', 10, '11 + the spell''s level', 50, 50, 1, 1, 'd8', 40, 0, 40, 0, 0, 60, 0, 0, 0, 10, 'Primordial, understands the languages you know', 'Summoned by: Summon Elemental|XPHB; Spell level: 4; Source: XPHB; PB: equals your Proficiency Bonus');
INSERT OR IGNORE INTO entity_stats (entity_id, strength, dexterity, constitution, intelligence, wisdom, charisma)
  VALUES ('mon-54', 18, 15, 17, 4, 10, 16);
INSERT OR IGNORE INTO creature_profiles (entity_id, challenge_rating, xp_value, creature_type, creature_subtype, is_legendary, legendary_resistances_max, legendary_resistances_current)
  VALUES ('mon-54', 0.0, 0, 'Elemental', NULL, 0, 0, 0);
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-54', id FROM action_library WHERE name = 'Multiattack';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-54', id FROM action_library WHERE name = 'Slam';
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-54', 'Poison', 'immunity');
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-54', 'Acid', 'resistance');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-54', 'Exhaustion');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-54', 'Paralyzed');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-54', 'Petrified');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-54', 'Poisoned');

INSERT OR IGNORE INTO entities (id, name, entity_type, size, alignment, armor_class, armor_desc, hit_points_max, hit_points_current, hit_dice_max, hit_dice_current, hit_dice_type, speed_walk, speed_fly, speed_swim, speed_climb, speed_burrow, darkvision, blindsight, tremorsense, truesight, passive_perception_override, languages, notes)
  VALUES ('mon-55', 'Fey Spirit (Fuming)', 'creature', 'Small', 'Neutral', 10, '12 + the spell''s level', 30, 30, 1, 1, 'd8', 30, 30, 0, 0, 0, 60, 0, 0, 0, 10, 'Sylvan, understands the languages you know', 'Summoned by: Summon Fey|XPHB; Spell level: 3; Source: XPHB; PB: equals your Proficiency Bonus');
INSERT OR IGNORE INTO entity_stats (entity_id, strength, dexterity, constitution, intelligence, wisdom, charisma)
  VALUES ('mon-55', 13, 16, 14, 14, 11, 16);
INSERT OR IGNORE INTO creature_profiles (entity_id, challenge_rating, xp_value, creature_type, creature_subtype, is_legendary, legendary_resistances_max, legendary_resistances_current)
  VALUES ('mon-55', 0.0, 0, 'Fey', NULL, 0, 0, 0);
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-55', id FROM action_library WHERE name = 'Multiattack';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-55', id FROM action_library WHERE name = 'Fey Blade';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-55', id FROM action_library WHERE name = 'Fey Step';
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-55', 'Charmed');

INSERT OR IGNORE INTO entities (id, name, entity_type, size, alignment, armor_class, armor_desc, hit_points_max, hit_points_current, hit_dice_max, hit_dice_current, hit_dice_type, speed_walk, speed_fly, speed_swim, speed_climb, speed_burrow, darkvision, blindsight, tremorsense, truesight, passive_perception_override, languages, notes)
  VALUES ('mon-56', 'Fey Spirit (Mirthful)', 'creature', 'Small', 'Neutral', 10, '12 + the spell''s level', 30, 30, 1, 1, 'd8', 30, 30, 0, 0, 0, 60, 0, 0, 0, 10, 'Sylvan, understands the languages you know', 'Summoned by: Summon Fey|XPHB; Spell level: 3; Source: XPHB; PB: equals your Proficiency Bonus');
INSERT OR IGNORE INTO entity_stats (entity_id, strength, dexterity, constitution, intelligence, wisdom, charisma)
  VALUES ('mon-56', 13, 16, 14, 14, 11, 16);
INSERT OR IGNORE INTO creature_profiles (entity_id, challenge_rating, xp_value, creature_type, creature_subtype, is_legendary, legendary_resistances_max, legendary_resistances_current)
  VALUES ('mon-56', 0.0, 0, 'Fey', NULL, 0, 0, 0);
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-56', id FROM action_library WHERE name = 'Multiattack';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-56', id FROM action_library WHERE name = 'Fey Blade';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-56', id FROM action_library WHERE name = 'Fey Step';
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-56', 'Charmed');

INSERT OR IGNORE INTO entities (id, name, entity_type, size, alignment, armor_class, armor_desc, hit_points_max, hit_points_current, hit_dice_max, hit_dice_current, hit_dice_type, speed_walk, speed_fly, speed_swim, speed_climb, speed_burrow, darkvision, blindsight, tremorsense, truesight, passive_perception_override, languages, notes)
  VALUES ('mon-57', 'Fey Spirit (Tricksy)', 'creature', 'Small', 'Neutral', 10, '12 + the spell''s level', 30, 30, 1, 1, 'd8', 30, 30, 0, 0, 0, 60, 0, 0, 0, 10, 'Sylvan, understands the languages you know', 'Summoned by: Summon Fey|XPHB; Spell level: 3; Source: XPHB; PB: equals your Proficiency Bonus');
INSERT OR IGNORE INTO entity_stats (entity_id, strength, dexterity, constitution, intelligence, wisdom, charisma)
  VALUES ('mon-57', 13, 16, 14, 14, 11, 16);
INSERT OR IGNORE INTO creature_profiles (entity_id, challenge_rating, xp_value, creature_type, creature_subtype, is_legendary, legendary_resistances_max, legendary_resistances_current)
  VALUES ('mon-57', 0.0, 0, 'Fey', NULL, 0, 0, 0);
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-57', id FROM action_library WHERE name = 'Multiattack';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-57', id FROM action_library WHERE name = 'Fey Blade';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-57', id FROM action_library WHERE name = 'Fey Step';
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-57', 'Charmed');

INSERT OR IGNORE INTO entities (id, name, entity_type, size, alignment, armor_class, armor_desc, hit_points_max, hit_points_current, hit_dice_max, hit_dice_current, hit_dice_type, speed_walk, speed_fly, speed_swim, speed_climb, speed_burrow, darkvision, blindsight, tremorsense, truesight, passive_perception_override, languages, notes)
  VALUES ('mon-58', 'Fiendish Spirit (Demon)', 'creature', 'Large', 'Neutral', 10, '12 + the spell''s level', 50, 50, 1, 1, 'd8', 40, 0, 0, 40, 0, 60, 0, 0, 0, 10, 'Abyssal, Infernal, Telepathy 60 ft.', 'Summoned by: Summon Fiend|XPHB; Spell level: 6; Source: XPHB; PB: equals your Proficiency Bonus');
INSERT OR IGNORE INTO entity_stats (entity_id, strength, dexterity, constitution, intelligence, wisdom, charisma)
  VALUES ('mon-58', 13, 16, 15, 10, 10, 16);
INSERT OR IGNORE INTO creature_profiles (entity_id, challenge_rating, xp_value, creature_type, creature_subtype, is_legendary, legendary_resistances_max, legendary_resistances_current)
  VALUES ('mon-58', 0.0, 0, 'Fiend', NULL, 0, 0, 0);
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-58', id FROM action_library WHERE name = 'Multiattack';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-58', id FROM action_library WHERE name = 'Bite';
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-58', 'Poison', 'immunity');
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-58', 'Fire', 'resistance');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-58', 'Poisoned');

INSERT OR IGNORE INTO entities (id, name, entity_type, size, alignment, armor_class, armor_desc, hit_points_max, hit_points_current, hit_dice_max, hit_dice_current, hit_dice_type, speed_walk, speed_fly, speed_swim, speed_climb, speed_burrow, darkvision, blindsight, tremorsense, truesight, passive_perception_override, languages, notes)
  VALUES ('mon-59', 'Fiendish Spirit (Devil)', 'creature', 'Large', 'Neutral', 10, '12 + the spell''s level', 40, 40, 1, 1, 'd8', 40, 60, 0, 0, 0, 60, 0, 0, 0, 10, 'Abyssal, Infernal, Telepathy 60 ft.', 'Summoned by: Summon Fiend|XPHB; Spell level: 6; Source: XPHB; PB: equals your Proficiency Bonus');
INSERT OR IGNORE INTO entity_stats (entity_id, strength, dexterity, constitution, intelligence, wisdom, charisma)
  VALUES ('mon-59', 13, 16, 15, 10, 10, 16);
INSERT OR IGNORE INTO creature_profiles (entity_id, challenge_rating, xp_value, creature_type, creature_subtype, is_legendary, legendary_resistances_max, legendary_resistances_current)
  VALUES ('mon-59', 0.0, 0, 'Fiend', NULL, 0, 0, 0);
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-59', id FROM action_library WHERE name = 'Multiattack';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-59', id FROM action_library WHERE name = 'Bite';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-59', id FROM action_library WHERE name = 'Fiery Strike';
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-59', 'Poison', 'immunity');
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-59', 'Fire', 'resistance');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-59', 'Poisoned');

INSERT OR IGNORE INTO entities (id, name, entity_type, size, alignment, armor_class, armor_desc, hit_points_max, hit_points_current, hit_dice_max, hit_dice_current, hit_dice_type, speed_walk, speed_fly, speed_swim, speed_climb, speed_burrow, darkvision, blindsight, tremorsense, truesight, passive_perception_override, languages, notes)
  VALUES ('mon-60', 'Fiendish Spirit (Yugoloth)', 'creature', 'Large', 'Neutral', 10, '12 + the spell''s level', 60, 60, 1, 1, 'd8', 40, 0, 0, 0, 0, 60, 0, 0, 0, 10, 'Abyssal, Infernal, Telepathy 60 ft.', 'Summoned by: Summon Fiend|XPHB; Spell level: 6; Source: XPHB; PB: equals your Proficiency Bonus');
INSERT OR IGNORE INTO entity_stats (entity_id, strength, dexterity, constitution, intelligence, wisdom, charisma)
  VALUES ('mon-60', 13, 16, 15, 10, 10, 16);
INSERT OR IGNORE INTO creature_profiles (entity_id, challenge_rating, xp_value, creature_type, creature_subtype, is_legendary, legendary_resistances_max, legendary_resistances_current)
  VALUES ('mon-60', 0.0, 0, 'Fiend', NULL, 0, 0, 0);
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-60', id FROM action_library WHERE name = 'Multiattack';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-60', id FROM action_library WHERE name = 'Bite';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-60', id FROM action_library WHERE name = 'Claws';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-60', id FROM action_library WHERE name = 'Fiery Strike';
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-60', 'Poison', 'immunity');
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-60', 'Fire', 'resistance');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-60', 'Poisoned');

INSERT OR IGNORE INTO entities (id, name, entity_type, size, alignment, armor_class, armor_desc, hit_points_max, hit_points_current, hit_dice_max, hit_dice_current, hit_dice_type, speed_walk, speed_fly, speed_swim, speed_climb, speed_burrow, darkvision, blindsight, tremorsense, truesight, passive_perception_override, languages, notes)
  VALUES ('mon-61', 'Giant Insect (Centipede)', 'creature', 'Large', 'Unaligned', 10, '11 + the spell''s level', 30, 30, 1, 1, 'd8', 40, 0, 0, 40, 0, 60, 0, 0, 0, 12, 'understands the languages you know', 'Summoned by: Giant Insect|XPHB; Spell level: 4; Source: XPHB; PB: equals your Proficiency Bonus');
INSERT OR IGNORE INTO entity_stats (entity_id, strength, dexterity, constitution, intelligence, wisdom, charisma)
  VALUES ('mon-61', 17, 13, 15, 4, 14, 3);
INSERT OR IGNORE INTO creature_profiles (entity_id, challenge_rating, xp_value, creature_type, creature_subtype, is_legendary, legendary_resistances_max, legendary_resistances_current)
  VALUES ('mon-61', 0.0, 0, 'Beast', NULL, 0, 0, 0);
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-61', id FROM action_library WHERE name = 'Multiattack';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-61', id FROM action_library WHERE name = 'Poison Jab';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-61', id FROM action_library WHERE name = 'Venomous Spew (Centipede Only)';

INSERT OR IGNORE INTO entities (id, name, entity_type, size, alignment, armor_class, armor_desc, hit_points_max, hit_points_current, hit_dice_max, hit_dice_current, hit_dice_type, speed_walk, speed_fly, speed_swim, speed_climb, speed_burrow, darkvision, blindsight, tremorsense, truesight, passive_perception_override, languages, notes)
  VALUES ('mon-62', 'Giant Insect (Spider)', 'creature', 'Large', 'Unaligned', 10, '11 + the spell''s level', 30, 30, 1, 1, 'd8', 40, 0, 0, 40, 0, 60, 0, 0, 0, 12, 'understands the languages you know', 'Summoned by: Giant Insect|XPHB; Spell level: 4; Source: XPHB; PB: equals your Proficiency Bonus');
INSERT OR IGNORE INTO entity_stats (entity_id, strength, dexterity, constitution, intelligence, wisdom, charisma)
  VALUES ('mon-62', 17, 13, 15, 4, 14, 3);
INSERT OR IGNORE INTO creature_profiles (entity_id, challenge_rating, xp_value, creature_type, creature_subtype, is_legendary, legendary_resistances_max, legendary_resistances_current)
  VALUES ('mon-62', 0.0, 0, 'Beast', NULL, 0, 0, 0);
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-62', id FROM action_library WHERE name = 'Multiattack';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-62', id FROM action_library WHERE name = 'Poison Jab';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-62', id FROM action_library WHERE name = 'Web Bolt';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-62', id FROM action_library WHERE name = 'Venomous Spew (Centipede Only)';

INSERT OR IGNORE INTO entities (id, name, entity_type, size, alignment, armor_class, armor_desc, hit_points_max, hit_points_current, hit_dice_max, hit_dice_current, hit_dice_type, speed_walk, speed_fly, speed_swim, speed_climb, speed_burrow, darkvision, blindsight, tremorsense, truesight, passive_perception_override, languages, notes)
  VALUES ('mon-63', 'Giant Insect (Wasp)', 'creature', 'Large', 'Unaligned', 10, '11 + the spell''s level', 30, 30, 1, 1, 'd8', 40, 40, 0, 40, 0, 60, 0, 0, 0, 12, 'understands the languages you know', 'Summoned by: Giant Insect|XPHB; Spell level: 4; Source: XPHB; PB: equals your Proficiency Bonus');
INSERT OR IGNORE INTO entity_stats (entity_id, strength, dexterity, constitution, intelligence, wisdom, charisma)
  VALUES ('mon-63', 17, 13, 15, 4, 14, 3);
INSERT OR IGNORE INTO creature_profiles (entity_id, challenge_rating, xp_value, creature_type, creature_subtype, is_legendary, legendary_resistances_max, legendary_resistances_current)
  VALUES ('mon-63', 0.0, 0, 'Beast', NULL, 0, 0, 0);
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-63', id FROM action_library WHERE name = 'Multiattack';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-63', id FROM action_library WHERE name = 'Poison Jab';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-63', id FROM action_library WHERE name = 'Web Bolt';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-63', id FROM action_library WHERE name = 'Venomous Spew (Centipede Only)';

INSERT OR IGNORE INTO entities (id, name, entity_type, size, alignment, armor_class, armor_desc, hit_points_max, hit_points_current, hit_dice_max, hit_dice_current, hit_dice_type, speed_walk, speed_fly, speed_swim, speed_climb, speed_burrow, darkvision, blindsight, tremorsense, truesight, passive_perception_override, languages, notes)
  VALUES ('mon-64', 'Otherworldly Steed (Celestial)', 'creature', 'Large', 'Neutral', 10, '10 + 1 per spell level', 5, 5, 1, 1, 'd8', 60, 60, 0, 0, 0, 0, 0, 0, 0, 11, 'telepathy 1 mile (works only with you)', 'Summoned by: Find Steed|XPHB; Spell level: 2; Source: XPHB; PB: equals your Proficiency Bonus');
INSERT OR IGNORE INTO entity_stats (entity_id, strength, dexterity, constitution, intelligence, wisdom, charisma)
  VALUES ('mon-64', 18, 12, 14, 6, 12, 8);
INSERT OR IGNORE INTO creature_profiles (entity_id, challenge_rating, xp_value, creature_type, creature_subtype, is_legendary, legendary_resistances_max, legendary_resistances_current)
  VALUES ('mon-64', 0.0, 0, 'Celestial', NULL, 0, 0, 0);
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-64', id FROM action_library WHERE name = 'Otherworldly Slam';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-64', id FROM action_library WHERE name = 'Healing Touch (Recharges after a Long Rest)';

INSERT OR IGNORE INTO entities (id, name, entity_type, size, alignment, armor_class, armor_desc, hit_points_max, hit_points_current, hit_dice_max, hit_dice_current, hit_dice_type, speed_walk, speed_fly, speed_swim, speed_climb, speed_burrow, darkvision, blindsight, tremorsense, truesight, passive_perception_override, languages, notes)
  VALUES ('mon-65', 'Otherworldly Steed (Fey)', 'creature', 'Large', 'Neutral', 10, '10 + 1 per spell level', 5, 5, 1, 1, 'd8', 60, 60, 0, 0, 0, 0, 0, 0, 0, 11, 'telepathy 1 mile (works only with you)', 'Summoned by: Find Steed|XPHB; Spell level: 2; Source: XPHB; PB: equals your Proficiency Bonus');
INSERT OR IGNORE INTO entity_stats (entity_id, strength, dexterity, constitution, intelligence, wisdom, charisma)
  VALUES ('mon-65', 18, 12, 14, 6, 12, 8);
INSERT OR IGNORE INTO creature_profiles (entity_id, challenge_rating, xp_value, creature_type, creature_subtype, is_legendary, legendary_resistances_max, legendary_resistances_current)
  VALUES ('mon-65', 0.0, 0, 'Fey', NULL, 0, 0, 0);
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-65', id FROM action_library WHERE name = 'Otherworldly Slam';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-65', id FROM action_library WHERE name = 'Fey Step (Recharges after a Long Rest)';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-65', id FROM action_library WHERE name = 'Healing Touch (Recharges after a Long Rest)';

INSERT OR IGNORE INTO entities (id, name, entity_type, size, alignment, armor_class, armor_desc, hit_points_max, hit_points_current, hit_dice_max, hit_dice_current, hit_dice_type, speed_walk, speed_fly, speed_swim, speed_climb, speed_burrow, darkvision, blindsight, tremorsense, truesight, passive_perception_override, languages, notes)
  VALUES ('mon-66', 'Otherworldly Steed (Fiend)', 'creature', 'Large', 'Neutral', 10, '10 + 1 per spell level', 5, 5, 1, 1, 'd8', 60, 60, 0, 0, 0, 0, 0, 0, 0, 11, 'telepathy 1 mile (works only with you)', 'Summoned by: Find Steed|XPHB; Spell level: 2; Source: XPHB; PB: equals your Proficiency Bonus');
INSERT OR IGNORE INTO entity_stats (entity_id, strength, dexterity, constitution, intelligence, wisdom, charisma)
  VALUES ('mon-66', 18, 12, 14, 6, 12, 8);
INSERT OR IGNORE INTO creature_profiles (entity_id, challenge_rating, xp_value, creature_type, creature_subtype, is_legendary, legendary_resistances_max, legendary_resistances_current)
  VALUES ('mon-66', 0.0, 0, 'Fiend', NULL, 0, 0, 0);
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-66', id FROM action_library WHERE name = 'Otherworldly Slam';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-66', id FROM action_library WHERE name = 'Fell Glare (Recharges after a Long Rest)';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-66', id FROM action_library WHERE name = 'Fey Step (Recharges after a Long Rest)';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-66', id FROM action_library WHERE name = 'Healing Touch (Recharges after a Long Rest)';

INSERT OR IGNORE INTO entities (id, name, entity_type, size, alignment, armor_class, armor_desc, hit_points_max, hit_points_current, hit_dice_max, hit_dice_current, hit_dice_type, speed_walk, speed_fly, speed_swim, speed_climb, speed_burrow, darkvision, blindsight, tremorsense, truesight, passive_perception_override, languages, notes)
  VALUES ('mon-67', 'Undead Spirit (Ghostly)', 'creature', 'Medium', 'Neutral', 10, '11 + the spell''s level', 30, 30, 1, 1, 'd8', 30, 40, 0, 0, 0, 60, 0, 0, 0, 10, 'understands the languages you know', 'Summoned by: Summon Undead|XPHB; Spell level: 3; Source: XPHB; PB: equals your Proficiency Bonus');
INSERT OR IGNORE INTO entity_stats (entity_id, strength, dexterity, constitution, intelligence, wisdom, charisma)
  VALUES ('mon-67', 12, 16, 15, 4, 10, 9);
INSERT OR IGNORE INTO creature_profiles (entity_id, challenge_rating, xp_value, creature_type, creature_subtype, is_legendary, legendary_resistances_max, legendary_resistances_current)
  VALUES ('mon-67', 0.0, 0, 'Undead', NULL, 0, 0, 0);
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-67', id FROM action_library WHERE name = 'Multiattack';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-67', id FROM action_library WHERE name = 'Deathly Touch';
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-67', 'Necrotic', 'immunity');
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-67', 'Poison', 'immunity');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-67', 'Exhaustion');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-67', 'Frightened');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-67', 'Paralyzed');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-67', 'Poisoned');

INSERT OR IGNORE INTO entities (id, name, entity_type, size, alignment, armor_class, armor_desc, hit_points_max, hit_points_current, hit_dice_max, hit_dice_current, hit_dice_type, speed_walk, speed_fly, speed_swim, speed_climb, speed_burrow, darkvision, blindsight, tremorsense, truesight, passive_perception_override, languages, notes)
  VALUES ('mon-68', 'Undead Spirit (Putrid)', 'creature', 'Medium', 'Neutral', 10, '11 + the spell''s level', 30, 30, 1, 1, 'd8', 30, 0, 0, 0, 0, 60, 0, 0, 0, 10, 'understands the languages you know', 'Summoned by: Summon Undead|XPHB; Spell level: 3; Source: XPHB; PB: equals your Proficiency Bonus');
INSERT OR IGNORE INTO entity_stats (entity_id, strength, dexterity, constitution, intelligence, wisdom, charisma)
  VALUES ('mon-68', 12, 16, 15, 4, 10, 9);
INSERT OR IGNORE INTO creature_profiles (entity_id, challenge_rating, xp_value, creature_type, creature_subtype, is_legendary, legendary_resistances_max, legendary_resistances_current)
  VALUES ('mon-68', 0.0, 0, 'Undead', NULL, 0, 0, 0);
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-68', id FROM action_library WHERE name = 'Multiattack';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-68', id FROM action_library WHERE name = 'Deathly Touch';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-68', id FROM action_library WHERE name = 'Rotting Claw';
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-68', 'Necrotic', 'immunity');
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-68', 'Poison', 'immunity');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-68', 'Exhaustion');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-68', 'Frightened');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-68', 'Paralyzed');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-68', 'Poisoned');

INSERT OR IGNORE INTO entities (id, name, entity_type, size, alignment, armor_class, armor_desc, hit_points_max, hit_points_current, hit_dice_max, hit_dice_current, hit_dice_type, speed_walk, speed_fly, speed_swim, speed_climb, speed_burrow, darkvision, blindsight, tremorsense, truesight, passive_perception_override, languages, notes)
  VALUES ('mon-69', 'Undead Spirit (Skeletal)', 'creature', 'Medium', 'Neutral', 10, '11 + the spell''s level', 20, 20, 1, 1, 'd8', 30, 0, 0, 0, 0, 60, 0, 0, 0, 10, 'understands the languages you know', 'Summoned by: Summon Undead|XPHB; Spell level: 3; Source: XPHB; PB: equals your Proficiency Bonus');
INSERT OR IGNORE INTO entity_stats (entity_id, strength, dexterity, constitution, intelligence, wisdom, charisma)
  VALUES ('mon-69', 12, 16, 15, 4, 10, 9);
INSERT OR IGNORE INTO creature_profiles (entity_id, challenge_rating, xp_value, creature_type, creature_subtype, is_legendary, legendary_resistances_max, legendary_resistances_current)
  VALUES ('mon-69', 0.0, 0, 'Undead', NULL, 0, 0, 0);
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-69', id FROM action_library WHERE name = 'Multiattack';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-69', id FROM action_library WHERE name = 'Deathly Touch';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-69', id FROM action_library WHERE name = 'Grave Bolt';
INSERT OR IGNORE INTO entity_actions (entity_id, action_id)
  SELECT 'mon-69', id FROM action_library WHERE name = 'Rotting Claw';
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-69', 'Necrotic', 'immunity');
INSERT OR IGNORE INTO entity_damage_modifiers (entity_id, damage_type, modifier_type)
  VALUES ('mon-69', 'Poison', 'immunity');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-69', 'Exhaustion');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-69', 'Frightened');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-69', 'Paralyzed');
INSERT OR IGNORE INTO entity_conditions (entity_id, condition_name)
  VALUES ('mon-69', 'Poisoned');

COMMIT;
